addons:
  chrome: stable
language: ruby
rvm:
  - 2.5.3
gemfile:
  - GemfileTravis
services:
  - xvfb
branches:
  only:
    - master
    - develop
    - /^v[0-9]+\.[0-9]+.[0-9]+$/
    - test
before_install:
  - gem install builder
  - BUILD_ONLY=true rake clean build
  - cd pkg; mkdir gems; mv ./*.gem ./gems; gem generate_index; cd ..
before_script:
  - nvm install 14.5.0
  - nvm use 14.5.0
  - export APPLITOOLS_BATCH_ID=$(java UUIDFromString $TRAVIS_COMMIT$TRAVIS_RUBY_VERSION)
  - echo $APPLITOOLS_BATCH_ID
  - export APPLITOOLS_DONT_CLOSE_BATCHES=true
  - echo $TRAVIS_TAG
  - if [[ ($TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$) || ($TRAVIS_TAG =~ ^RELEASE_CANDIDATE) ]]; then
      export TEST_REPORT_SANDBOX=False;
      export SDK_VERSION=$(echo $TRAVIS_TAG | sed 's/[^.0-9]*//g');
      export TMP_CHANGELOG=$(bash ./extractChangeLog.sh "$SDK_VERSION" "CHANGELOG.md");
      export CHANGELOG=$([ -z "$TMP_CHANGELOG" ] && echo "There is no change log for version $SDK_VERSION"; echo "$TMP_CHANGELOG");

      if [[ (-z "$TMP_CHANGELOG") ]]; then
        echo "THE CHANGELOG IS NOT CORRECT";
        exit 1;
      fi
    fi
jobs:
  include:
    - stage: "Unit Tests"
      name: "Unit Tests"
      script: bundle exec rake unit_tests:travis
    - stage: "Ruby Coverage tests"
      name: "Ruby Coverage tests"
      script: yarn ruby:prod
    - stage: "Tutorials tests"
      script:
        - cd pkg/gems; gem install eyes_selenium; cd ../..
        - mkdir tutorials && git clone https://github.com/applitools/tutorial-selenium-ruby-basic.git
        - cd tutorials/tutorial-selenium-ruby-basic
        - ruby simple_test_script.rb