addons:
  chrome: stable

language: ruby
rvm:
  - 2.4.5
gemfile:
  - GemfileTravis
services:
  - xvfb
branches:
  only:
    - master
    - develop
before_install:
  - gem install builder
  - BUILD_ONLY=true rake clean build
  - cd pkg; mkdir gems; mv ./*.gem ./gems; gem generate_index; cd ..
before_script:
  - export APPLITOOLS_BATCH_ID=$(java UUIDFromString $TRAVIS_COMMIT$TRAVIS_RUBY_VERSION)
  - echo $APPLITOOLS_BATCH_ID
  - export APPLITOOLS_DONT_CLOSE_BATCHES=true
jobs:
  include:
    - stage: "Unit Tests"
      name: "Unit Tests"
      script: bundle exec rake unit_tests:travis
    - stage: "Visual tests"
      name: "Classic Selenium"
      script: bundle exec rake travis_selenium
    - script: bundle exec rake travis_vg
      name: "Visual Grid"
