dist: trusty
addons:
  chrome: stable

language: ruby
rvm:
  - 2.4.1
gemfile:
  - GemfileTravis

sudo: false
branches:
  only:
    - master
    - /^v.*$/
before_install:
  - gem install builder
  - BUILD_ONLY=true rake clean build
  - cd pkg; mkdir gems; mv ./*.gem ./gems; gem generate_index; cd ..
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
  - wget http://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/build
  - sudo mv -f /home/travis/build/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  - sudo apt-get install -y libgdiplus
  - export APPLITOOLS_BATCH_ID=$(java UUIDFromString $TRAVIS_COMMIT$TRAVIS_RUBY_VERSION)
  - echo $APPLITOOLS_BATCH_ID
script:
  - bundle exec rake
